version: '3.8'
services:
 mongodb:
  image: mongo
  container_name: mongo
  restart: always
  command: --nojournal
  networks:
  - TheNetwork
  ports:
  - "27017:27017"
 mongo-seed:
  build: ./Mongodb
  depends_on:
  - mongodb
  environment:
  - MONGO_HOST=mongo
  - MONGO_PORT=27017
  command: "mongoimport --host mongo --port 27017 -d agile_data_science -c origin_dest_distances --mode upsert --file /practica_big_data_2019/resources/data/origin_dest_distances.jsonl"
  networks:
  - TheNetwork
 web:
  container_name: servidorweb
  build: ./ServidorWeb
  ports:
   - "5000:5000"
  networks:
   - TheNetwork
 zookeeper:
  container_name: zk
  image: wurstmeister/zookeeper
  ports:
   - "2181:2181"
  networks:
   - TheNetwork
 kafka:
  container_name: kafka
  image: wurstmeister/kafka
  hostname: kafka
  environment:
   KAFKA_ADVERTISED_HOST_NAME: kafka
   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"
   KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
   KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
   KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  depends_on:
   - zookeeper
  ports:
   - "9092:9092"
  networks:
   - TheNetwork
 spark-master:
  build: ./SparkMaster
  container_name: spark-master
  ports:
   - "8080:8080"
   - "7077:7077"
  environment:
   - INIT_DAEMON_STEP=setup_spark
  networks:
   - TheNetwork
  volumes:
   - ./data:/opt
   - ./apps:/spark-apps
 spark-worker-1:
  build: ./worker
  container_name: spark-worker-1
  depends_on:
   - spark-master
  ports:
   - "8081:8081"
  environment:
   - SPARK_MASTER=spark://spark-master:7077
   - SPARK_WORKER_CORES=1
   - SPARK_WORKER_MEMORY=1G
   - SPARK_DRIVER_MEMORY=1G
   - SPARK_EXECUTOR_MEMORY=1G
  networks:
   - TheNetwork
  volumes:
   - ./data:/opt
   - ./apps:/spark-apps
 spark-worker-2:
  build: ./worker
  container_name: spark-worker-2
  depends_on:
   - spark-master
  ports:
   - "8082:8082"
  environment:
   - SPARK_MASTER=spark://spark-master:7077
   - SPARK_WORKER_CORES=1
   - SPARK_WORKER_MEMORY=1G
   - SPARK_DRIVER_MEMORY=1G
   - SPARK_EXECUTOR_MEMORY=1G
  networks:
   - TheNetwork
  volumes:
   - ./data:/opt
   - ./apps:/spark-apps
networks:
  TheNetwork:
